<?php

namespace ZF\MvcRbac\Identity;

use ZF\MvcAuth\Identity\AuthenticatedIdentity as MvcAuthenticatedIdentity;

class AuthenticatedIdentity extends MvcAuthenticatedIdentity
{
    protected $role;

    public function getRoleId()
    {
        return parent::getRoleId(); // TODO: Change the autogenerated stub
    }

}